#!/usr/bin/env bash

if [ $# -lt 1 ]; then
  crun -h
  exit 0
fi

options=""

# If the terminal is not set, suppress stdout
if [ "${TERM:-dumb}" = "dumb" ]; then
  options="--quiet"
fi

exec crun -c=/etc/crun/crun.toml $@
